#ifndef __KBD_LAYOUT_SCAN_CODES_US_H__
#define __KBD_LAYOUT_SCAN_CODES_US_H__
#include "lufa-key-codes.h"

// `x1234567890-=qwertyuiop[]asdfghjkl;'\<zxcvbnm,./

static key_map_t kbd_layout_scan_codes[] = {
	/* char, scan code (PC scancode), LUFA HID keycode */
	{'`',  0x29, HID_KEYBOARD_SC_GRAVE_ACCENT_AND_TILDE},
	{'1',  0x02, HID_KEYBOARD_SC_1_AND_EXCLAMATION},
	{'2',  0x03, HID_KEYBOARD_SC_2_AND_AT},
	{'3',  0x04, HID_KEYBOARD_SC_3_AND_HASHMARK},
	{'4',  0x05, HID_KEYBOARD_SC_4_AND_DOLLAR},
	{'5',  0x06, HID_KEYBOARD_SC_5_AND_PERCENTAGE},
	{'6',  0x07, HID_KEYBOARD_SC_6_AND_CARET},
	{'7',  0x08, HID_KEYBOARD_SC_7_AND_AMPERSAND},
	{'8',  0x09, HID_KEYBOARD_SC_8_AND_ASTERISK},
	{'9',  0x0A, HID_KEYBOARD_SC_9_AND_OPENING_PARENTHESIS},
	{'0',  0x0B, HID_KEYBOARD_SC_0_AND_CLOSING_PARENTHESIS},
	{'-',  0x0C, HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE},
	{'=',  0x0D, HID_KEYBOARD_SC_EQUAL_AND_PLUS},
	{'q',  0x10, HID_KEYBOARD_SC_Q},
	{'w',  0x11, HID_KEYBOARD_SC_W},
	{'e',  0x12, HID_KEYBOARD_SC_E},
	{'r',  0x13, HID_KEYBOARD_SC_R},
	{'t',  0x14, HID_KEYBOARD_SC_T},
	{'y',  0x15, HID_KEYBOARD_SC_Y},
	{'u',  0x16, HID_KEYBOARD_SC_U},
	{'i',  0x17, HID_KEYBOARD_SC_I},
	{'o',  0x18, HID_KEYBOARD_SC_O},
	{'p',  0x19, HID_KEYBOARD_SC_P},
	{'[',  0x1A, HID_KEYBOARD_SC_OPENING_BRACKET_AND_OPENING_BRACE},
	{']',  0x1B, HID_KEYBOARD_SC_CLOSING_BRACKET_AND_CLOSING_BRACE},
	{'a',  0x1E, HID_KEYBOARD_SC_A},
	{'s',  0x1F, HID_KEYBOARD_SC_S},
	{'d',  0x20, HID_KEYBOARD_SC_D},
	{'f',  0x21, HID_KEYBOARD_SC_F},
	{'g',  0x22, HID_KEYBOARD_SC_G},
	{'h',  0x23, HID_KEYBOARD_SC_H},
	{'j',  0x24, HID_KEYBOARD_SC_J},
	{'k',  0x25, HID_KEYBOARD_SC_K},
	{'l',  0x26, HID_KEYBOARD_SC_L},
	{';',  0x27, HID_KEYBOARD_SC_SEMICOLON_AND_COLON},
	{'\'', 0x28, HID_KEYBOARD_SC_APOSTROPHE_AND_QUOTE},
	{'\\', 0x2B, HID_KEYBOARD_SC_BACKSLASH_AND_PIPE},
	{'<',  0x56, HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN},
	{'z',  0x2C, HID_KEYBOARD_SC_Z},
	{'x',  0x2D, HID_KEYBOARD_SC_X},
	{'c',  0x2E, HID_KEYBOARD_SC_C},
	{'v',  0x2F, HID_KEYBOARD_SC_V},
	{'b',  0x30, HID_KEYBOARD_SC_B},
	{'n',  0x31, HID_KEYBOARD_SC_N},
	{'m',  0x32, HID_KEYBOARD_SC_M},
	{',',  0x33, HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN},
	{'.',  0x34, HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN},
	{'/',  0x35, HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK},
	/* these are always constant on all keyboards */
	{'\n', 0x1C, HID_KEYBOARD_SC_ENTER},
	{'\t', 0x0F, HID_KEYBOARD_SC_TAB},
	{' ',  0x39, HID_KEYBOARD_SC_SPACE},
};

#endif
